### ISSUE TITLE
Errors with square brackets

### ISSUE THREAD

**Issue by anton-vidext** [DeepLcom/deepl-node#19] opened 2023-02-08 16:08 UTC
**Describe the bug**
When translating strings that contains square brackets it doesn't work well. It duplicates the content and removes the first bracket.

It's also happening in the web version.

**To Reproduce**
1. Go to following link and check the result yourself :)

https://www.deepl.com/translator?share=generic#es/en/%20%5B1s%5D%20%5B1s%5D%20%5B1s%5D%20%5B1s%5D%20%5B1s%5D

**Expected behavior**

 [1s] [1s] [1s] [1s] [1s]
**Screenshots**

![web](https://user-images.githubusercontent.com/107871283/217584635-e89267b4-b2b3-4b9b-986f-4cba8c09e4a8.jpg)

**Comment by andoni-enriquez** [comment] 2023-02-08 16:37
Sometimes it also replaces [1s] to (1s)

**Comment by anton-vidext** [comment] 2023-02-08 16:37
![web2](https://user-images.githubusercontent.com/107871283/217593581-5926390e-10a7-4a43-bd1d-ce790c317c5e.jpg)

**Comment by seekuehe** [comment] 2023-04-25 14:57
Hi @anton-vidext,

Thank you for your report. We have informed the responsible team about the issue.

Since this is not a node library issue, I will close this ticket. If you encounter any other unexpected behavior related to translation, you can also contact support@deepl.com.

**Closed by seekuehe** 2023-04-25 14:57 UTC
