### ISSUE TITLE
translation using arrays does not work

### ISSUE THREAD

**Issue by LorenzoJokhan** [DeepLcom/deepl-node#10] opened 2022-10-11 13:53 UTC
Good day, i am trying to translate a big array with deepl. Somehow when i put even a small array in the translateText function i am getting an error: 

DeepLError: texts parameter must not be a non-empty string or array of non-empty strings at appendTextsAndReturnIsSingular   projectpath/node_modules/deepl-node/dist/index.js:166:23

It seems that arrays are not supported

 translator.translateText(
                ['hallo', 'test'],
                req.body.sourceLanguageCode, //this is nl
                req.body.targetLanguageCode, // this is en-GB
            )

**Comment by daniel-jones-deepl** [comment] 2022-10-11 14:22
Hi @LorenzoJokhan, thanks for creating the issue.

Unfortunately I haven't been able to reproduce this. The library includes [this test case](https://github.com/DeepLcom/deepl-node/blob/main/tests/translateText.test.ts#L19) in the tests. Are you using a [supported node version](https://github.com/DeepLcom/deepl-node#requirements)?

**Comment by LorenzoJokhan** [comment] 2022-10-11 14:45
Ik heb in de functie appendTextsAndReturnIsSingular(data, texts) wat console logs gedaan en krijg het volgende:

{ textsIsArray: true }
{ arrayToTranslate: [ 'tekst', 'welkom' ] }
keys: 0, 1, insert

error: DeepLError: texts parameter must not be a non-empty string or array of non-empty strings

**Comment by daniel-jones-deepl** [comment] 2022-10-11 14:57
Thanks, but I could not reproduce this behavior either; the key "insert" does not appear. Does the `texts` array come from an unusual source?

**Comment by LorenzoJokhan** [comment] 2022-10-12 07:27
It seems a developer at my current project added a key to the prototype of array (which is not a good thing to do). Meaning that every array at our side will have that function as a key. This would mean however that if you choose to continue to use a for...in loop in deepl translation, then in the future when another library modifies the prototype they will also have these issues. 

Array.prototype.insert = function ( index, item ) {
    this.splice( index, 0, item );
};

The easiest fool-proof fix would be to change the loop to a for...of loop or standard for loop that only iterates over the elements instead of the keys

**Comment by daniel-jones-deepl** [comment] 2022-10-12 08:37
Thank you for your reply, that explains the cause.

You are right about using `for .. of` loops, we'll fix this soon.

**Comment by daniel-jones-deepl** [comment] 2022-10-12 09:30
This is fixed in [v1.7.1](https://github.com/DeepLcom/deepl-node/blob/main/CHANGELOG.md#171---2022-10-12).

**Closed by daniel-jones-deepl** 2022-10-12 09:30 UTC
