### ISSUE TITLE
autotranslate does not work

### ISSUE THREAD

**Issue by svumme** [DeepLcom/deepl-node#6] opened 2022-07-28 20:29 UTC
today autotranslate does not work, until yesterday it worked fine, today the language detected is the same as the target language

**Comment by daniel-jones-deepl** [comment] 2022-08-01 07:48
Hi @svumme, thanks for reporting the issue. Can you please give more information, for example the input you used?

**Comment by daniel-jones-deepl** [comment] 2022-09-30 08:20
I'm closing this issue as we cannot reproduce it without more information. Feel free to comment again in future.

**Closed by daniel-jones-deepl** 2022-09-30 08:20 UTC
Labels: question
